# Homework 01 
1. Numpy 
2. Pytorch (tensor (basic operations))

# DEADLINE

### IS-142 - 08.10.24 
### IS-141 - 15.10.24

## Блок №1 (numpy) 

1. Импортировать NumPy под именем np

In [25]:
import numpy as np

2. Создать вектор (одномерный массив) размера 20, заполненный нулями

In [26]:
v = np.zeros(20)
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

3. Создать вектор размера 20, заполненный числом 1.75

In [27]:
v = np.ones(20) * 1.75
v

array([1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75,
       1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75, 1.75])

4. Создать вектор со значениями от 4 до 31

In [94]:
v = np.arange(4, 32)
v

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

5. Развернуть вектор (первый становится последним)

In [95]:
v[::-1]

array([31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

6. Создать матрицу (двумерный массив) 3x3 со значениями от 1 до 9

In [96]:
m = np.arange(9).reshape(3, 3) + 1
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

7. Создать 3x3 единичную матрицу

In [97]:
m = np.identity(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

8. Создать 4x4 пустую матрицу

In [98]:
m = np.zeros(16).reshape(4, 4)
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

9. Создать единичную матрицу 4x4 со сдвигом на единицу вниз относительно главной диагонали

In [99]:
m = np.eye(4, k=-1)
m

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

10. Создать тензор 3x3x3 со случайными значениями

In [100]:
t = np.random.random((3, 3, 3))
t

array([[[0.98081313, 0.64438323, 0.76666749],
        [0.72699573, 0.00982599, 0.59376148],
        [0.08346069, 0.82322979, 0.26388481]],

       [[0.47108603, 0.85781918, 0.31569949],
        [0.14002295, 0.59962434, 0.38176381],
        [0.38360741, 0.37015914, 0.84876713]],

       [[0.64182964, 0.5759163 , 0.23098222],
        [0.39729712, 0.30002003, 0.33520289],
        [0.49070854, 0.05243478, 0.66205141]]])

11. Создать массив 5x5 со случайными значениями, найти минимум и максимум

In [47]:
v = np.random.random((5, 5))
v, v.min(), v.max()

(array([[0.22396263, 0.9952618 , 0.68470622, 0.56404335, 0.4722401 ],
        [0.89703615, 0.63594232, 0.00543759, 0.93710644, 0.43496406],
        [0.02392361, 0.37601843, 0.70333953, 0.14241446, 0.95590988],
        [0.07415857, 0.16511831, 0.28451465, 0.85707882, 0.7987108 ],
        [0.23396874, 0.51491806, 0.8397648 , 0.87590824, 0.20953132]]),
 0.005437588114210912,
 0.995261795370718)

12. Создать случайный вектор размера 50 и найти среднее значение всех элементов

In [48]:
v = np.random.random(50)
v, np.mean(v)

(array([0.89614324, 0.07178343, 0.23949833, 0.42922324, 0.59167879,
        0.58455765, 0.01564424, 0.50726149, 0.51824202, 0.25853483,
        0.00292691, 0.83549008, 0.14299177, 0.43970386, 0.03255122,
        0.95763742, 0.94158474, 0.40539911, 0.7268332 , 0.99184879,
        0.08116831, 0.56364242, 0.40073073, 0.61318508, 0.25873846,
        0.44829571, 0.34766356, 0.93642348, 0.75492341, 0.74552965,
        0.40239503, 0.13620655, 0.44957351, 0.55941437, 0.45175348,
        0.86823797, 0.37569649, 0.89854795, 0.19386614, 0.33636209,
        0.78895103, 0.65860875, 0.550602  , 0.58176526, 0.35483593,
        0.47830103, 0.49136431, 0.77936538, 0.06265398, 0.37971744]),
 0.49076107751835724)

13. Создать матрицу с 0 внутри, и 1 на границах

In [101]:
m = np.ones((5, 5))
m[1:-1, 1:-1] = 0
m

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

14. Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [102]:
m = np.diag([1, 2, 3, 4], k=-1)
m

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

15. Перемножить матрицы 5x3 и 3x2

In [39]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
C = np.dot(A, B)
A, B, C

(array([[0.73834423, 0.07533818, 0.73751314],
        [0.40021889, 0.489683  , 0.8193449 ],
        [0.14081835, 0.53146937, 0.304283  ],
        [0.42221428, 0.26028856, 0.35333802],
        [0.44893037, 0.67143267, 0.26666174]]),
 array([[0.04595997, 0.06258868],
        [0.64454187, 0.13699877],
        [0.10229064, 0.47017925]]),
 array([[0.15793358, 0.4032966 ],
        [0.41782656, 0.47737411],
        [0.38015157, 0.22469184],
        [0.223315  , 0.22821725],
        [0.48067629, 0.24546223]]))

16. Создать вектор состоящий из 15 элементов, поменять знак у элементов, значения которых между 6 и 12 

In [51]:
v = np.arange(15)
v[(v > 6) & (v < 12)] *= -1
v

array([  0,   1,   2,   3,   4,   5,   6,  -7,  -8,  -9, -10, -11,  12,
        13,  14])

17. Создать 2 матрицы A(3x3) и B(3x3), получить матрицу С путем поэлеметного умножения.

In [41]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
C = A * B
A, B, C

(array([[0.72425235, 0.55197462, 0.95206016],
        [0.92892184, 0.04895057, 0.71943451],
        [0.66253917, 0.82504207, 0.88074677]]),
 array([[0.06852257, 0.12017596, 0.32001412],
        [0.31604952, 0.97321125, 0.73203979],
        [0.76991206, 0.9499254 , 0.2229418 ]]),
 array([[0.04962763, 0.06633408, 0.3046727 ],
        [0.2935853 , 0.04763925, 0.52665469],
        [0.5100969 , 0.78372842, 0.19635527]]))

18. Найти максимальные и минимальные значения матрицы С по строкам и столбцам

In [42]:
min_by_rows = C.min(axis=1)
max_by_rows = C.max(axis=1)
min_by_cols = C.min(axis=0)
max_by_cols = C.max(axis=0)
print(f"Min by rows: {min_by_rows}\nMax by rows: {max_by_rows}")
print(f"Min by cols: {min_by_cols}\nMax by cols: {max_by_cols}")

Min by rows: [0.04962763 0.04763925 0.19635527]
Max by rows: [0.3046727  0.52665469 0.78372842]
Min by cols: [0.04962763 0.04763925 0.19635527]
Max by cols: [0.5100969  0.78372842 0.52665469]


19. Создать вектор со значениями от 0 до 1 c 10 наблюдениями

In [52]:
v = np.random.random(10)
v

array([0.40574202, 0.41815269, 0.42436304, 0.7776159 , 0.13155804,
       0.10547867, 0.17388103, 0.85877688, 0.96446387, 0.98873422])

20. Отсортировать вектор

In [53]:
np.sort(v)

array([0.10547867, 0.13155804, 0.17388103, 0.40574202, 0.41815269,
       0.42436304, 0.7776159 , 0.85877688, 0.96446387, 0.98873422])

21. Проверить, одинаковы ли 2 numpy массива

In [103]:
a1 = np.random.random(10)
a2 = np.random.random(10)
a3 = a1
np.array_equal(a1, a2), np.array_equal(a1, a3)

(False, True)

22. Сделать массив неизменяемым

In [55]:
immut = np.random.random(10)
immut.flags.writeable = False
immut[1] = 0

ValueError: assignment destination is read-only

23. Создать случайный вектор из 20 элементов, найти квантиль от 10% и от 80%

In [56]:
v = np.random.random(20)
np.quantile(v, 0.1), np.quantile(v, 0.8)

(0.21854186438288234, 0.7300684931338449)

24. Создать массив любой размерности состоящий из int и string

In [46]:
mixed = np.array([1, 'a', 2, 'b'], dtype=object)
print(mixed)

[1 'a' 2 'b']


25. Найти минимальное и максимальное значение, принимаемое каждым числовым типом numpy

In [57]:
int_min = np.iinfo(np.int32).min
int_max = np.iinfo(np.int32).max
float_min = np.finfo(np.float32).min
float_max = np.finfo(np.float32).max
print(f"Int32 Min: {int_min}, Int32 Max: {int_max}")
print(f"Float32 Min: {float_min}, Float32 Max: {float_max}")

Int32 Min: -2147483648, Int32 Max: 2147483647
Float32 Min: -3.4028234663852886e+38, Float32 Max: 3.4028234663852886e+38


26. Преобразовать массив из float в int

In [58]:
f_v = np.random.random(10) * 10
i_v = f_v.astype(int)
f_v, i_v

(array([0.91828669, 1.11155552, 7.56224572, 1.07495286, 6.70543349,
        2.84957214, 8.86005516, 6.93037285, 7.48140566, 7.7251224 ]),
 array([0, 1, 7, 1, 6, 2, 8, 6, 7, 7]))

27. Отнять среднее из каждой строки в матрице

In [104]:
m = np.random.random((5, 5))
m_sub_mean = m - m.mean(axis=1, keepdims=True)
m, m_sub_mean

(array([[0.85965631, 0.76597205, 0.66913233, 0.13672823, 0.12572228],
        [0.84596352, 0.71313169, 0.47677775, 0.1638451 , 0.20629115],
        [0.52194328, 0.46457936, 0.25163192, 0.51511978, 0.96646266],
        [0.56842546, 0.73313583, 0.08197223, 0.84425068, 0.39170305],
        [0.85111305, 0.70305801, 0.3895157 , 0.41017463, 0.44327468]]),
 array([[ 0.34821407,  0.25452981,  0.15769009, -0.37471401, -0.38571996],
        [ 0.36476167,  0.23192985, -0.00442409, -0.31735674, -0.27491069],
        [-0.02200413, -0.07936804, -0.29231548, -0.02882762,  0.42251526],
        [ 0.04452801,  0.20923838, -0.44192522,  0.32035323, -0.1321944 ],
        [ 0.29168583,  0.14363079, -0.16991151, -0.14925259, -0.11615253]]))

28. Считать данные из файла в матрицу:

1,2,3,4,5

6,,,7,8

,,9,10,11

In [105]:
from io import StringIO
data = "1,2,3,4,5\n6,,,7,8\n,,9,10,11"
file_like = StringIO(data)
m = np.genfromtxt(file_like, delimiter=',')
m

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

29. Посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [63]:
np.sum(np.arange(1, 10001) ** 2)

333383335000

## Блок №2 (tensors) 

1. Импортируйте pytorch

In [64]:
import torch

2. Создать вектор состящий из 10 элементов

In [65]:
v = torch.arange(10)
v

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

3. Создать тензор из python list

In [106]:
l = [1, 2, 3, 4, 5]
t = torch.tensor(l)
t

tensor([1, 2, 3, 4, 5])

4. Создать тензор из np.array

In [107]:
a = np.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3])

5. Создать тензор с нормальным распределением

In [108]:
t = torch.randn(3, 3)
t

tensor([[-0.5709, -2.3233, -0.5542],
        [ 0.1098,  0.0845,  1.8254],
        [ 1.2071,  0.0041, -0.4621]])

6. Создать тензор размером 3х3х3

In [109]:
t = torch.randn(3, 3, 3)
t

tensor([[[ 0.0526,  1.4299, -0.1356],
         [-0.9425, -1.3444, -0.5788],
         [-0.7768,  1.0004, -1.8233]],

        [[-1.4237,  1.9474, -0.3987],
         [ 0.5899, -1.7014,  0.0395],
         [ 0.9188, -0.9355, -0.0111]],

        [[-0.4869,  0.5911, -2.4739],
         [-0.8242, -0.2972,  1.2371],
         [-1.4110, -0.9487,  1.0955]]])

7. Создать единичную матрицу размером 4х5

In [110]:
m = torch.eye(4, 5)
m

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.]])

8. Создать вектор размера 25, заполнить елементами со значениме pi

In [73]:
v = torch.full((25,), torch.pi)
v

tensor([3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416,
        3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416, 3.1416])

9. Умножить матрицу размера 9, заполненная от 0 до 8, поэлементно на любое число

In [111]:
m = torch.arange(9).reshape(3, 3)
m * 2

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

10. Создать произвольный тензор с типом данных int8

In [112]:
t = torch.randint(-128, 127, (3, 3), dtype=torch.int8)
t

tensor([[  38, -113,   54],
        [  94,   26,   23],
        [ -56,   37,   79]], dtype=torch.int8)

11. Изменить тип данных из пункта 10 на int64

In [113]:
t = t.to(torch.int64)
t

tensor([[  38, -113,   54],
        [  94,   26,   23],
        [ -56,   37,   79]])

12. Создать случайный тензор размера 4x5 и найти среднее по 2му столбцу.

In [114]:
t = torch.randn(4, 5)
t[:, 1].mean()

tensor(-0.0432)

13. Создать пустой тензор произвольных размеров

In [115]:
t = torch.empty(3, 3)
t

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

14. Скалярно умножить 2 вектора

In [79]:
v1 = torch.randn(3)
v2 = torch.randn(3)
v1, v2, torch.dot(v1, v2)

(tensor([-0.1522,  0.6546, -2.2158]),
 tensor([ 0.0989, -0.3107, -0.6497]),
 tensor(1.2212))

15. Умножить матрицу на вектор

In [80]:
m = torch.randn(3, 3)
v = torch.randn(3)
torch.mv(m, v)

tensor([-0.5214, -2.0414, -0.4453])

16. Перемножить 2D матрицы 

In [81]:
m1 = torch.randn(3, 3)
m2 = torch.randn(3, 3)
m1, m2, torch.mm(m1, m2)

(tensor([[ 1.0365, -0.1938, -0.3358],
         [ 0.9832,  0.7667, -0.2571],
         [ 0.5128,  0.4905,  1.3715]]),
 tensor([[ 2.0556,  1.1470, -0.4785],
         [ 1.6802, -0.0731,  0.2884],
         [-0.5335, -1.6660,  1.0897]]),
 tensor([[ 1.9842,  1.7624, -0.9178],
         [ 3.4466,  1.5000, -0.5295],
         [ 1.1465, -1.7327,  1.3907]]))

17. Перемножить 3D тензоры

In [82]:
t1 = torch.randn(3, 3, 3)
t2 = torch.randn(3, 3, 3)
t1, t2, t1 * t2

(tensor([[[ 1.5305e-01,  3.4788e-01,  2.0563e-03],
          [-1.4021e+00, -1.3216e-01,  9.4837e-01],
          [-7.2144e-01, -9.2185e-01, -7.9716e-01]],
 
         [[-7.0347e-01, -6.9835e-01,  1.5531e-01],
          [ 1.1448e+00,  7.6270e-01, -2.0976e+00],
          [ 5.5873e-01,  1.5169e-01,  8.1130e-01]],
 
         [[-4.0597e-01,  2.4635e-01, -4.7985e-01],
          [ 5.2654e-01, -1.0965e+00,  1.4762e+00],
          [ 6.1960e-01,  6.1866e-01,  6.5985e-02]]]),
 tensor([[[-2.1784e+00, -3.3868e-01, -1.6884e+00],
          [-1.3358e+00,  9.3327e-01,  1.6494e-03],
          [ 1.7165e+00, -1.3496e-01,  2.3726e-01]],
 
         [[ 5.9812e-01,  3.2135e-01, -6.9744e-01],
          [-1.3037e+00, -1.2206e+00,  3.6493e-02],
          [ 5.0670e-01, -1.4488e+00,  1.1490e+00]],
 
         [[ 1.0053e+00, -3.8710e-01,  1.2252e+00],
          [-5.7075e-01, -3.8750e-01, -4.5118e-01],
          [ 2.0711e-01, -3.7343e-02,  1.0960e+00]]]),
 tensor([[[-3.3341e-01, -1.1782e-01, -3.4719e-03],
          [ 1

18. Создать вектор с нормальным распределением и вывести элементы больше 0.5

In [83]:
v = torch.randn(10)
v[v > 0.5]

tensor([0.6014, 0.9066, 0.7294])

19. Создать матрицу 3х3 заполненную единицами и заменить 1й столбец на 4

In [84]:
m = torch.ones(3, 3)
m[:, 0] = 4
m

tensor([[4., 1., 1.],
        [4., 1., 1.],
        [4., 1., 1.]])

20. Создать матрицу и вывести сумму по каждой строке

In [85]:
m = torch.randn(3, 3)
m.sum(dim=1)

tensor([ 2.8169,  0.4715, -0.9179])

20. Создать матрицу и вывести среднее по каждому столбцу

In [86]:
m.mean(dim=0)

tensor([ 0.3038,  1.1936, -0.7072])

21. Создать 2 вектора и сконкатенировать по 1 оси

In [87]:
v1 = torch.randn(5)
v2 = torch.randn(5)
torch.cat((v1.unsqueeze(0), v2.unsqueeze(0)), dim=0)

tensor([[-0.6190, -0.6860,  1.3188,  0.1347, -0.3523],
        [ 1.7197,  1.3446, -0.4745, -1.3977, -1.1771]])

22. Перемножим две большие единичные матрицы. 
Сначал на центральном процессоре, затем попробуйте на GPU

In [93]:
m1 = torch.randn(1000, 1000)
m2 = torch.randn(1000, 1000)
print(torch.mm(m1, m2))

if torch.cuda.is_available():
    m1_cuda = m1.cuda()
    m2_cuda = m2.cuda()
    gpu_result = torch.mm(m1_cuda, m2_cuda)
    print(gpu_result)

tensor([[-13.0941,  78.6451, -17.6467,  ...,  46.4466, -14.9382,  10.4500],
        [ -2.6750,  -6.2654,  -7.7626,  ..., -33.5780,  32.5051,   7.1309],
        [-60.1090,  25.8206, -37.2353,  ...,  -7.6859,  -1.2693,  42.4814],
        ...,
        [ -7.9530,   0.4959,   9.6289,  ...,  29.0874,  -7.0077,  11.2747],
        [ 12.2239,   5.0612, -23.3883,  ...,  12.5764,  15.5697,  15.5738],
        [-28.4863,  56.1503,  33.6479,  ..., -33.5866,   5.4467,   5.1504]])
